server:
  port: 8080

spring:
  application:
    name: PRODUCT-SERVICE

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://eureka-0.eureka:8761/eureka}